# Generated by Django 5.2.6 on 2025-09-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ielts_exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
