# Generated by Django 5.2.6 on 2025-09-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_ielts_exam_date'),
        ('accounts', '0002_userprofile_onboarding_completed'),
    ]

    operations = [
    ]
