# Generated by Django 5.2.6 on 2025-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0004_userloginlog_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
