# Generated by Django 5.2.6 on 2025-09-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_studentprogress'),
        ('education', '0002_university_level_drop_currency'),
    ]

    operations = [
    ]
