# Generated by Django 5.2.6 on 2025-09-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_remove_university_founded_year_university_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='founded_year',
        ),
        migrations.AddField(
            model_name='university',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
