# Generated by Django 5.2.6 on 2025-09-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_userevent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
